name: Feature
description: New product or engineering feature
title: "[Feature] "
labels: ["feature"]
body:
  - type: textarea
    id: goal
    attributes:
      label: Goal
    validations:
      required: true

  - type: textarea
    id: requirements
    attributes:
      label: Requirements
    validations:
      required: true

  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      value: |
        - [ ]
        - [ ]
        - [ ]
