name: Engineering Task
description: Internal engineering task
title: "[Task] "
labels: ["task"]
body:
  - type: textarea
    id: goal
    attributes:
      label: Goal
    validations:
      required: true

  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      value: |
        - [ ]
        - [ ]
        - [ ]
